In [1]:
import pandas as pd
import requests
from sklearn import preprocessing

In [2]:
start = 200
end = 250

In [3]:
pd.set_option('display.max_rows', 500)

In [4]:
match_summary_df = pd.read_csv('../data/encoded_match_data.csv')

In [5]:
match_summary_df = match_summary_df[match_summary_df['league'] == 0][start:end]

In [6]:
len(match_summary_df)

42

In [7]:
match_summary_df.columns

Index(['league', 'format', 'game_in_format', 'red_team_outcome',
       'blue_team_outcome', 'season_format', 'riot_match_id', 'min_start_time',
       'month', 'day', 'year', 'red_team_id', 'blue_team_id', 'winner_id',
       'loser_id'],
      dtype='object')

In [8]:
match_summary_df.head(10)

,league,format,game_in_format,red_team_outcome,blue_team_outcome,season_format,riot_match_id,min_start_time,month,day,year,red_team_id,blue_team_id,winner_id,loser_id
200,0,1,1,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2125,2117,2117,2125
201,0,1,2,1,0,1,111561337007305519,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125,2117,2125
202,0,1,1,1,0,1,111561337007239862,2024-01-27 06:00:00+00:00,1,27,2024,2118,2145,2118,2145
203,0,1,2,0,1,1,111561337007239863,2024-01-27 06:00:00+00:00,1,27,2024,2118,2145,2145,2118
204,0,1,3,1,0,1,111561337007239864,2024-01-27 07:19:36+00:00,1,27,2024,2145,2118,2145,2118
205,0,1,1,0,1,1,111561337007239846,2024-01-26 10:30:00+00:00,1,26,2024,2119,2124,2124,2119
206,0,1,2,0,1,1,111561337007239847,2024-01-26 10:30:00+00:00,1,26,2024,2124,2119,2119,2124
207,0,1,3,1,0,1,111561337007239848,2024-01-26 11:44:14+00:00,1,26,2024,2124,2119,2124,2119
208,0,1,1,0,1,1,111561337007305510,2024-01-26 08:00:00+00:00,1,26,2024,2144,2123,2123,2144
209,0,1,2,0,1,1,111561337007305511,2024-01-26 08:00:00+00:00,1,26,2024,2123,2144,2144,2123

In [9]:
columns=match_summary_df.columns.to_list()
columns.extend(['patch_version'])

for clr in ['blue','red']:
    columns.append(F"{clr}_team_id")
    for pos in ['top','jungle','mid','bot','supp']:
        col = F"{clr}_{pos}_player"
        columns.append(col)
        col = F"{clr}_{pos}_champ"
        columns.append(col)

columns.extend(['rfc460Timestamp'])
for clr in ['blue','red']:
    for info in ['total_gold','inhibitors','towers','barons','total_kills','ocean_drakes','cloud_drakes','mountain_drakes','chemtech_drakes','infernal_drakes','hextech_drakes','elder_drakes']:
        col = F"{clr}_team_{info}"
        columns.append(col)

    for pos in ['top','jungle','mid','bot','supp']:
        for info in ['total_gold','level','kills','deaths','assists','creep_score','current_health','max_health']:
            col = F"{clr}_{pos}_{info}"
            columns.append(col)

In [10]:
columns

['league',
 'format',
 'game_in_format',
 'red_team_outcome',
 'blue_team_outcome',
 'season_format',
 'riot_match_id',
 'min_start_time',
 'month',
 'day',
 'year',
 'red_team_id',
 'blue_team_id',
 'winner_id',
 'loser_id',
 'patch_version',
 'blue_team_id',
 'blue_top_player',
 'blue_top_champ',
 'blue_jungle_player',
 'blue_jungle_champ',
 'blue_mid_player',
 'blue_mid_champ',
 'blue_bot_player',
 'blue_bot_champ',
 'blue_supp_player',
 'blue_supp_champ',
 'red_team_id',
 'red_top_player',
 'red_top_champ',
 'red_jungle_player',
 'red_jungle_champ',
 'red_mid_player',
 'red_mid_champ',
 'red_bot_player',
 'red_bot_champ',
 'red_supp_player',
 'red_supp_champ',
 'rfc460Timestamp',
 'blue_team_total_gold',
 'blue_team_inhibitors',
 'blue_team_towers',
 'blue_team_barons',
 'blue_team_total_kills',
 'blue_team_ocean_drakes',
 'blue_team_cloud_drakes',
 'blue_team_mountain_drakes',
 'blue_team_chemtech_drakes',
 'blue_team_infernal_drakes',
 'blue_team_hextech_drakes',
 'blue_team_elder_drakes',
 'blue_top_total_gold',
 'blue_top_level',
 'blue_top_kills',
 'blue_top_deaths',
 'blue_top_assists',
 'blue_top_creep_score',
 'blue_top_current_health',
 'blue_top_max_health',
 'blue_jungle_total_gold',
 'blue_jungle_level',
 'blue_jungle_kills',
 'blue_jungle_deaths',
 'blue_jungle_assists',
 'blue_jungle_creep_score',
 'blue_jungle_current_health',
 'blue_jungle_max_health',
 'blue_mid_total_gold',
 'blue_mid_level',
 'blue_mid_kills',
 'blue_mid_deaths',
 'blue_mid_assists',
 'blue_mid_creep_score',
 'blue_mid_current_health',
 'blue_mid_max_health',
 'blue_bot_total_gold',
 'blue_bot_level',
 'blue_bot_kills',
 'blue_bot_deaths',
 'blue_bot_assists',
 'blue_bot_creep_score',
 'blue_bot_current_health',
 'blue_bot_max_health',
 'blue_supp_total_gold',
 'blue_supp_level',
 'blue_supp_kills',
 'blue_supp_deaths',
 'blue_supp_assists',
 'blue_supp_creep_score',
 'blue_supp_current_health',
 'blue_supp_max_health',
 'red_team_total_gold',
 'red_team_inhibitors',
 'red_team_towers',
 'red_team_barons',
 'red_team_total_kills',
 'red_team_ocean_drakes',
 'red_team_cloud_drakes',
 'red_team_mountain_drakes',
 'red_team_chemtech_drakes',
 'red_team_infernal_drakes',
 'red_team_hextech_drakes',
 'red_team_elder_drakes',
 'red_top_total_gold',
 'red_top_level',
 'red_top_kills',
 'red_top_deaths',
 'red_top_assists',
 'red_top_creep_score',
 'red_top_current_health',
 'red_top_max_health',
 'red_jungle_total_gold',
 'red_jungle_level',
 'red_jungle_kills',
 'red_jungle_deaths',
 'red_jungle_assists',
 'red_jungle_creep_score',
 'red_jungle_current_health',
 'red_jungle_max_health',
 'red_mid_total_gold',
 'red_mid_level',
 'red_mid_kills',
 'red_mid_deaths',
 'red_mid_assists',
 'red_mid_creep_score',
 'red_mid_current_health',
 'red_mid_max_health',
 'red_bot_total_gold',
 'red_bot_level',
 'red_bot_kills',
 'red_bot_deaths',
 'red_bot_assists',
 'red_bot_creep_score',
 'red_bot_current_health',
 'red_bot_max_health',
 'red_supp_total_gold',
 'red_supp_level',
 'red_supp_kills',
 'red_supp_deaths',
 'red_supp_assists',
 'red_supp_creep_score',
 'red_supp_current_health',
 'red_supp_max_health']

In [11]:
match_data_df = pd.DataFrame(columns=columns)

In [12]:
match_data_df

Empty DataFrame
Columns: [league, format, game_in_format, red_team_outcome, blue_team_outcome, season_format, riot_match_id, min_start_time, month, day, year, red_team_id, blue_team_id, winner_id, loser_id, patch_version, blue_team_id, blue_top_player, blue_top_champ, blue_jungle_player, blue_jungle_champ, blue_mid_player, blue_mid_champ, blue_bot_player, blue_bot_champ, blue_supp_player, blue_supp_champ, red_team_id, red_top_player, red_top_champ, red_jungle_player, red_jungle_champ, red_mid_player, red_mid_champ, red_bot_player, red_bot_champ, red_supp_player, red_supp_champ, rfc460Timestamp, blue_team_total_gold, blue_team_inhibitors, blue_team_towers, blue_team_barons, blue_team_total_kills, blue_team_ocean_drakes, blue_team_cloud_drakes, blue_team_mountain_drakes, blue_team_chemtech_drakes, blue_team_infernal_drakes, blue_team_hextech_drakes, blue_team_elder_drakes, blue_top_total_gold, blue_top_level, blue_top_kills, blue_top_deaths, blue_top_assists, blue_top_creep_score, blue_top_current_health, blue_top_max_health, blue_jungle_total_gold, blue_jungle_level, blue_jungle_kills, blue_jungle_deaths, blue_jungle_assists, blue_jungle_creep_score, blue_jungle_current_health, blue_jungle_max_health, blue_mid_total_gold, blue_mid_level, blue_mid_kills, blue_mid_deaths, blue_mid_assists, blue_mid_creep_score, blue_mid_current_health, blue_mid_max_health, blue_bot_total_gold, blue_bot_level, blue_bot_kills, blue_bot_deaths, blue_bot_assists, blue_bot_creep_score, blue_bot_current_health, blue_bot_max_health, blue_supp_total_gold, blue_supp_level, blue_supp_kills, blue_supp_deaths, blue_supp_assists, blue_supp_creep_score, blue_supp_current_health, blue_supp_max_health, red_team_total_gold, red_team_inhibitors, red_team_towers, red_team_barons, red_team_total_kills, red_team_ocean_drakes, red_team_cloud_drakes, red_team_mountain_drakes, red_team_chemtech_drakes, ...]
Index: []

[0 rows x 143 columns]

In [13]:
def extract_fixed_info(json_data):
    ret_data = dict()
    ret_data['patch_version'] = json_data['gameMetadata']['patchVersion']
    ret_data['blue_team_id'] = json_data['gameMetadata']['blueTeamMetadata']['esportsTeamId']
    for i,pos in enumerate(['top','jungle','mid','bot','supp']):

        ret_data[F'blue_{pos}_player'] = json_data['gameMetadata']['blueTeamMetadata']['participantMetadata'][i]['esportsPlayerId']
        ret_data[F'blue_{pos}_champ'] = json_data['gameMetadata']['blueTeamMetadata']['participantMetadata'][i]['championId']

    ret_data['red_team_id'] = json_data['gameMetadata']['redTeamMetadata']['esportsTeamId']
    for i,pos in enumerate(['top','jungle','mid','bot','supp']):

        ret_data[F'red_{pos}_player'] = json_data['gameMetadata']['redTeamMetadata']['participantMetadata'][i]['esportsPlayerId']
        ret_data[F'red_{pos}_champ'] = json_data['gameMetadata']['redTeamMetadata']['participantMetadata'][i]['championId']

    return ret_data

In [14]:
def encode_dragons(team,info):
    ret_data = dict()
    for drake in ['ocean_drakes','cloud_drakes','mountain_drakes','chemtech_drakes','infernal_drakes','hextech_drakes','elder_drakes']:
        ret_data[F"{team}_{drake}"] = 0
    for d in info:
        k = F"{team}_{d}_drakes"
        ret_data[k] = ret_data[k] + 1
    
    return ret_data

In [15]:
def extract_changing_info(json_data):
    ret_data = dict()
    # ret_data['rfc460Timestamp'] = json_data['rfc460Timestamp']
    for clr in ['blue','red']:
        ret_data[F'{clr}_team_total_gold'] = json_data[F'{clr}Team']['totalGold']
        ret_data[F'{clr}_team_inhibitors'] = json_data[F'{clr}Team']['inhibitors']
        ret_data[F'{clr}_team_towers'] = json_data[F'{clr}Team']['towers']
        ret_data[F'{clr}_team_barons'] = json_data[F'{clr}Team']['barons']
        ret_data[F'{clr}_team_total_kills'] = json_data[F'{clr}Team']['totalKills']
        ret_data.update(encode_dragons(F'{clr}_team',json_data[F'{clr}Team']['dragons']))

        for i,pos in enumerate(['top','jungle','mid','bot','supp']):
            ret_data[F'{clr}_{pos}_total_gold'] = json_data[F'{clr}Team']['participants'][i]['totalGold']
            ret_data[F'{clr}_{pos}_level'] = json_data[F'{clr}Team']['participants'][i]['level']
            ret_data[F'{clr}_{pos}_kills'] = json_data[F'{clr}Team']['participants'][i]['kills']
            ret_data[F'{clr}_{pos}_deaths'] = json_data[F'{clr}Team']['participants'][i]['deaths']
            ret_data[F'{clr}_{pos}_assists'] = json_data[F'{clr}Team']['participants'][i]['assists']
            ret_data[F'{clr}_{pos}_creep_score'] = json_data[F'{clr}Team']['participants'][i]['creepScore']
            ret_data[F'{clr}_{pos}_current_health'] = json_data[F'{clr}Team']['participants'][i]['currentHealth']
            ret_data[F'{clr}_{pos}_max_health'] = json_data[F'{clr}Team']['participants'][i]['maxHealth']


    return ret_data

In [16]:
BASE_URL = 'https://feed.lolesports.com/livestats/v1/window/{}?startingTime={}'

In [17]:
def format_time(t,time_delta):
    conv_time = pd.to_datetime(t) + pd.to_timedelta(time_delta, unit='s')
    conv_time = conv_time.round('10s')
    return "{}T{}.000Z".format(str(conv_time.date()),str(conv_time.time()))

In [18]:
time_delta = 60
temp_list = []

for index, row in match_summary_df.iterrows():
    print(index)
    print(row)
    game_state = "in_game"
    fixed_info = None
    time_elapsed = 0

    while game_state == "in_game":

        url = BASE_URL.format(row['riot_match_id'],format_time(row['min_start_time'],time_elapsed))
        raw_data = requests.get(url)

        time_elapsed = time_elapsed + time_delta
        if raw_data.status_code == 204: # No content returned
            continue

        data = raw_data.json()
        if fixed_info == None:
            fixed_info = extract_fixed_info(data)

        prev_frame = data['frames'][0]
        for frame in data['frames'][1:]:
            delta_info = extract_changing_info(frame)
            if delta_info == prev_frame:
                continue
            delta_info.update(fixed_info)
            delta_info['rfc460Timestamp'] = frame['rfc460Timestamp']
            delta_info.update(row)
            temp_list.append(delta_info)
            prev_frame = delta_info


        game_state = data['frames'][-1]['gameState']

200
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305518
min_start_time       2024-01-27 08:30:00+00:00
month                                        1
day                                         27
year                                      2024
red_team_id                               2125
blue_team_id                              2117
winner_id                                 2117
loser_id                                  2125
Name: 200, dtype: object
201
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007305519
min_start_time       2024-01-27 08:30:00+00:00
month                                        1
day                                         27
year                                      2024
red_team_id                               2117
blue_team_id                              2125
winner_id                                 2117
loser_id                                  2125
Name: 201, dtype: object
202
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239862
min_start_time       2024-01-27 06:00:00+00:00
month                                        1
day                                         27
year                                      2024
red_team_id                               2118
blue_team_id                              2145
winner_id                                 2118
loser_id                                  2145
Name: 202, dtype: object
203
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239863
min_start_time       2024-01-27 06:00:00+00:00
month                                        1
day                                         27
year                                      2024
red_team_id                               2118
blue_team_id                              2145
winner_id                                 2145
loser_id                                  2118
Name: 203, dtype: object
204
league                                       0
format                                       1
game_in_format                               3
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239864
min_start_time       2024-01-27 07:19:36+00:00
month                                        1
day                                         27
year                                      2024
red_team_id                               2145
blue_team_id                              2118
winner_id                                 2145
loser_id                                  2118
Name: 204, dtype: object
205
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239846
min_start_time       2024-01-26 10:30:00+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2119
blue_team_id                              2124
winner_id                                 2124
loser_id                                  2119
Name: 205, dtype: object
206
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239847
min_start_time       2024-01-26 10:30:00+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2124
blue_team_id                              2119
winner_id                                 2119
loser_id                                  2124
Name: 206, dtype: object
207
league                                       0
format                                       1
game_in_format                               3
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239848
min_start_time       2024-01-26 11:44:14+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2124
blue_team_id                              2119
winner_id                                 2124
loser_id                                  2119
Name: 207, dtype: object
208
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305510
min_start_time       2024-01-26 08:00:00+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2144
blue_team_id                              2123
winner_id                                 2123
loser_id                                  2144
Name: 208, dtype: object
209
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305511
min_start_time       2024-01-26 08:00:00+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2123
blue_team_id                              2144
winner_id                                 2144
loser_id                                  2123
Name: 209, dtype: object
210
league                                       0
format                                       1
game_in_format                               3
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007305512
min_start_time       2024-01-26 08:56:41+00:00
month                                        1
day                                         26
year                                      2024
red_team_id                               2144
blue_team_id                              2123
winner_id                                 2144
loser_id                                  2123
Name: 210, dtype: object
211
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239890
min_start_time       2024-01-25 10:30:00+00:00
month                                        1
day                                         25
year                                      2024
red_team_id                               2145
blue_team_id                              2120
winner_id                                 2145
loser_id                                  2120
Name: 211, dtype: object
212
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239891
min_start_time       2024-01-25 10:30:00+00:00
month                                        1
day                                         25
year                                      2024
red_team_id                               2145
blue_team_id                              2120
winner_id                                 2145
loser_id                                  2120
Name: 212, dtype: object
213
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239882
min_start_time       2024-01-25 08:00:00+00:00
month                                        1
day                                         25
year                                      2024
red_team_id                               2125
blue_team_id                              2118
winner_id                                 2118
loser_id                                  2125
Name: 213, dtype: object
214
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239883
min_start_time       2024-01-25 08:00:00+00:00
month                                        1
day                                         25
year                                      2024
red_team_id                               2118
blue_team_id                              2125
winner_id                                 2118
loser_id                                  2125
Name: 214, dtype: object
215
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305498
min_start_time       2024-01-24 10:30:00+00:00
month                                        1
day                                         24
year                                      2024
red_team_id                               2117
blue_team_id                              2123
winner_id                                 2123
loser_id                                  2117
Name: 215, dtype: object
216
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007305499
min_start_time       2024-01-24 10:30:00+00:00
month                                        1
day                                         24
year                                      2024
red_team_id                               2117
blue_team_id                              2123
winner_id                                 2117
loser_id                                  2123
Name: 216, dtype: object
217
league                                       0
format                                       1
game_in_format                               3
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007305500
min_start_time       2024-01-24 11:41:46+00:00
month                                        1
day                                         24
year                                      2024
red_team_id                               2117
blue_team_id                              2123
winner_id                                 2117
loser_id                                  2123
Name: 217, dtype: object
218
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007305486
min_start_time       2024-01-24 08:00:00+00:00
month                                        1
day                                         24
year                                      2024
red_team_id                               2122
blue_team_id                              2124
winner_id                                 2122
loser_id                                  2124
Name: 218, dtype: object
219
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305487
min_start_time       2024-01-24 08:00:00+00:00
month                                        1
day                                         24
year                                      2024
red_team_id                               2124
blue_team_id                              2122
winner_id                                 2122
loser_id                                  2124
Name: 219, dtype: object
220
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239870
min_start_time       2024-01-21 08:30:00+00:00
month                                        1
day                                         21
year                                      2024
red_team_id                               2123
blue_team_id                              2118
winner_id                                 2118
loser_id                                  2123
Name: 220, dtype: object
221
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239871
min_start_time       2024-01-21 08:30:00+00:00
month                                        1
day                                         21
year                                      2024
red_team_id                               2118
blue_team_id                              2123
winner_id                                 2123
loser_id                                  2118
Name: 221, dtype: object
222
league                                       0
format                                       1
game_in_format                               3
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239872
min_start_time       2024-01-21 09:40:44+00:00
month                                        1
day                                         21
year                                      2024
red_team_id                               2123
blue_team_id                              2118
winner_id                                 2123
loser_id                                  2118
Name: 222, dtype: object
223
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305482
min_start_time       2024-01-21 06:00:00+00:00
month                                        1
day                                         21
year                                      2024
red_team_id                               2117
blue_team_id                              2122
winner_id                                 2122
loser_id                                  2117
Name: 223, dtype: object
224
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007305483
min_start_time       2024-01-21 06:00:00+00:00
month                                        1
day                                         21
year                                      2024
red_team_id                               2117
blue_team_id                              2122
winner_id                                 2122
loser_id                                  2117
Name: 224, dtype: object
225
league                                       0
format                                       1
game_in_format                               1
red_team_outcome                             1
blue_team_outcome                            0
season_format                                1
riot_match_id               111561337007239934
min_start_time       2024-01-20 08:30:00+00:00
month                                        1
day                                         20
year                                      2024
red_team_id                               2145
blue_team_id                              2125
winner_id                                 2145
loser_id                                  2125
Name: 225, dtype: object
226
league                                       0
format                                       1
game_in_format                               2
red_team_outcome                             0
blue_team_outcome                            1
season_format                                1
riot_match_id               111561337007239935
min_start_time       2024-01-20 08:30:00+00:00
month                                        1
day                                         20
year                                      2024
red_team_id                               2125
blue_team_id                              2145
winner_id                                 2145
loser_id                                  2125
Name: 226, dtype: object
227
league                                       0
format                                       1
game_in_format                               1

In [19]:
match_data_df = pd.DataFrame.from_dict(temp_list)

In [20]:
match_data_df.head()

,blue_team_total_gold,blue_team_inhibitors,blue_team_towers,blue_team_barons,blue_team_total_kills,blue_team_ocean_drakes,blue_team_cloud_drakes,blue_team_mountain_drakes,blue_team_chemtech_drakes,blue_team_infernal_drakes,...,red_team_outcome,blue_team_outcome,season_format,riot_match_id,min_start_time,month,day,year,winner_id,loser_id
0,2500,0,0,0,0,0,0,0,0,0,...,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125
1,2500,0,0,0,0,0,0,0,0,0,...,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125
2,2500,0,0,0,0,0,0,0,0,0,...,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125
3,2500,0,0,0,0,0,0,0,0,0,...,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125
4,2500,0,0,0,0,0,0,0,0,0,...,0,1,1,111561337007305518,2024-01-27 08:30:00+00:00,1,27,2024,2117,2125

In [21]:
match_data_df.to_csv(F'../data/match_time_data_LCK_{start}_{end}.csv',index=False)